version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-image
jobs:
  build-image:
    docker:
      - image: docker:git
    environment:
      PGBOUNCER_VERSION: 1.14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build --build-arg PGBOUNCER_VERSION=${PGBOUNCER_VERSION} -t ${DOCKER_USER}/container-pgbouncer:${PGBOUNCER_VERSION}-amd64 .
            docker tag ${DOCKER_USER}/container-pgbouncer:${PGBOUNCER_VERSION}-amd64 ${DOCKER_USER}/container-pgbouncer:latest
      - run:
          name: upload image to docker hub.
          command: |
            docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}
            docker push ${DOCKER_USER}/container-pgbouncer:${PGBOUNCER_VERSION}-amd64
